name: Make binary
on: [workflow_dispatch]

jobs:
    make:
        strategy:
            matrix:
                node-version: [16.x]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - name: Install deps
              run: npm ci
            - name: Install ncc
              run: npm install --global @vercel/ncc
            - name: Install pkg
              run: npm install --global pkg
            - name: Create dist/
              run: mkdir dist
            - name: Run ncc
              run: ncc build esm.js -o dist
            - name: Run pkg
              run: pkg dist/index.js
            - uses: actions/upload-artifact@v3
              with:
                  name: Example-Linux
                  path: index-linux
            - uses: actions/upload-artifact@v3
              with:
                  name: Example-MacOS
                  path: index-macos
            - uses: actions/upload-artifact@v3
              with:
                  name: Example-Windows
                  path: index-win.exe
