name: GitHub Actions Demo
on:
    workflow_dispatch:
        inputs:
            seed:
                description: 'Arbitrary string'
                required: true
jobs:
    demo:
        strategy:
            matrix:
                node-version: [16.x, 18.x]
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - name: Print npm version
              run: npm -v
            - name: Install deps
              run: npm ci
            - name: Print git status
              run: node git-status.js
            - name: Print process.env
              run: node process-env.js
            - name: Install complementary repository
              run: npm install git+https://github.com/Cafe137/gh-ci-complement.git#
            - name: Run complementary repository
              run: node node_modules/gh-ci-complement/index.js
            - name: Install Bee dashboard
              run: npm install https://github.com/ethersphere/bee-dashboard/tarball/master
